from .Add_MessDetail_View import Add_Mess_Details
from .Add_New_Dish_view import Add_New_Dish_View
from .Delete_Mess_Details_view import Delete_Mess_Details_view
from .Update_Mess_Details import Update_Mess_Details